### ISSUE TITLE
saving data into mysql 

### ISSUE THREAD

**Issue by adamrifau** [dnaextrim/php_zklib#16]
how to save  data into mysql
i've tried several steps but seems doesn't work does anyone know how to save data into mysql db

if (isset($_POST['create_post'])) {

          $query = "INSERT INTO attendance(idx)";
          $query .= "VALUES ($id)";
          $submittodbquery = mysqli_query($con,$query);
          if (!$submittodbquery) {
          die("Failed up upload " . mysqli_error($con));
        }else {
          echo "updated";
        }

        }

**Comment by shubhamoy** [comment]
It houses an SQLite DB and you can actually take a backup from the device menu. After that, you can convert it.
