### ISSUE TITLE
Can you give us all manual that you have

### ISSUE THREAD

**Issue by Dmo3** [dnaextrim/php_zklib#20]
Hi ,, 

Can you upload all manual that you are used to develop this class..

Best Regards,,,

**Comment by suryacaprice** [comment]
[pyzk (1).pdf](https://github.com/dnaextrim/php_zklib/files/1248689/pyzk.1.pdf)
[Communication_protocol_manual_CMD.pdf](https://github.com/dnaextrim/php_zklib/files/1248693/Communication_protocol_manual_CMD.pdf)

Here is the file i found for development

**Comment by suryacaprice** [comment]
please let me know if you update the code

**Comment by Dmo3** [comment]
Thanks for the fast replay
