### ISSUE TITLE
Youtube Channel With Manual And Related SDK

### ISSUE THREAD

**Issue by Ailyn09** [dnaextrim/php_zklib#21]
Hi,

Great script!

Actually I tried all the code and sdk of the device. And I got Fatal error https://stackoverflow.com/questions/45951222/php-zklib-undefined-function-socket-create. 

> Fatal error: Uncaught Error: Call to undefined function socket_create() in C:\xampp\htdocs\php_zklib-master\zklib\zklib.php:16 Stack trace: #0 C:\xampp\htdocs\php_zklib-master\zktest.php(10): ZKLib->__construct('192.168.5.164', 4370) #1 {main} thrown in C:\xampp\htdocs\php_zklib-master\zklib\zklib.php on line 16

Can you create a youtube channel about this in order for us to easily get the follow and understand the way how to use this.
And please add the following manual and SDK if needed for this program and how to use each.

I hope for a favorable and positive response.

Thanks.

**Comment by ferchuse** [comment]
Hi, you need to enable the php_socket extension. https://stackoverflow.com/questions/1361925/how-to-enable-socket-in-php
