### ISSUE TITLE
Get Attendance format

### ISSUE THREAD

**Issue by RahamSher** [dnaextrim/php_zklib#24]
@suryacaprice & @junaidranjha I have the array of all attendances.My array structure is like this.
            [0] => 1
            [1] => 1
            **[2] => 8 //it is state.What does this means for???**
            [3] => 2016-12-27 11:51:33

And one more thing that I have all the attendances of users,Please guide me that how I differentiate the check in and check out of user.

**Comment by shubhamoy** [comment]
Here are the states.
0 => Check-In (default value) 
1 => Check-Out 
2 => Break Out
3 => Break In 
4 => Over Time In 
5 => Over Time Out
